In [1]:
from window_slider import Slider
import numpy
list = numpy.array([0, 1, 2, 3, 4, 5, 6, 7])
bucket_size = 3
overlap_count = 1
slider = Slider(bucket_size,overlap_count)
slider.fit(list)       
while True:
    window_data = slider.slide()
    # do your stuff
    print(window_data)
    if slider.reached_end_of_list(): break
        
#Source: https://pypi.org/project/window-slider/

[0 1 2]
[2 3 4]
[4 5 6]
[6 7]
